package-name: apache-airflow-providers-isolation
display-name: Isolated Operators
docs_url: https://github.com/astronomer/apache-airflow-providers-isolation/blob/main/README.md

hooks:
  - module: isolation.hooks.post_isolation.PostIsolationHook

operators:
  - module: isolation.operators.isolation.IsolationOperator
  - module: isolation.operators.isolation_kubernetes.IsolatedKubernetesPodOperator
