name: pre-commit

on:
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dev dependencies
        run: pip install '.[dev]'
      - name: Run pre-commit
        run: |
          git fetch origin
          pre-commit run --from-ref origin/${{ github.event.pull_request.base.ref }} --to-ref ${{ github.event.pull_request.head.sha }}
      - name: Test with pytest
        run: pytest -c pyproject.toml --cov=./ --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
